### ISSUE TITLE
解析主从节点出错

### ISSUE THREAD

**Issue by marscqy** [GoDannyLai/trident#2]
time="2018-05-14_16:41:08" level=info errcode=0 msg="check 172.27.25.35:7000 is redis or cluster"
time="2018-05-14_16:41:08" level=info errcode=0 msg="172.27.25.35:7000 is cluster"
time="2018-05-14_16:41:08" level=info errcode=0 msg="start to get latest slaves to scan keys"
time="2018-05-14_16:41:08" level=error errcode=903 msg="fail to get latest slaves to scan keys" stacktrace="*errors.errorString dial tcp: address tcp/7002@17002: unknown port\n\t/root/trident/trident-master/src/dannytools/ehand/errhandle.go:76 (0x4d875e)\n\t\tWithStackError: serr := errors.Errorf(err.Error())\n\t/root/trident/trident-master/src/dannytools/myredis/redis.go:34 (0x662cc4)\n\t\tConfRedis.CreateNewClientRedis: return nil, ehand.WithStackError(err)\n\t/root/trident/trident-master/src/dannytools/myredis/common.go:1025 (0x6623b1)\n\t\tGetLatestSlaveOfMasters: redisClient, err = redisConf.CreateNewClientRedis()\n\t/root/trident/trident-master/trident.go:169 (0x669d5c)\n\t\tGetNodesAddrToScanKey: _, slaves, masters, err := myredis.GetLatestSlaveOfMasters(allMasters)\n\t/root/trident/trident-master/main.go:31 (0x665907)\n\t\tmain: nodesScan := GetNodesAddrToScanKey(g_conf)\n\t/usr/go/src/runtime/proc.go:198 (0x42be62)\n\t\tmain: fn()\n\t/usr/go/src/runtime/asm_amd64.s:2361 (0x455f21)\n\t\tgoexit: BYTE\t$0x90\t// NOP\n\t"
time="2018-05-14_16:41:08" level=error msg="Error Exits!"

127.0.0.1:7000> cluster nodes
cc6ef7526eb0fda69db23fcfe035d1218e8cca72 172.27.25.35:7003@17003 slave 2a1ada71bb3072fe746f1d73732cd8b094fb05c6 0 1526287370672 4 connected
c5aa4190b7990f42ef5c0789f0b3405e97e6be99 172.27.25.35:7001@17001 master - 0 1526287370000 2 connected 5461-10922
97377d50894fac373a1fd9c3dc827fb596916ebd 172.27.25.35:7005@17005 slave c5aa4190b7990f42ef5c0789f0b3405e97e6be99 0 1526287369570 6 connected
7377a4b4c8f7ed985e3974d89042bb9db6bac709 172.27.25.35:7004@17004 slave ac0e63ee858a0109486121fe0cb16ed841ee8321 0 1526287369000 5 connected
2a1ada71bb3072fe746f1d73732cd8b094fb05c6 172.27.25.35:7002@17002 master - 0 1526287370000 3 connected 10923-16383
ac0e63ee858a0109486121fe0cb16ed841ee8321 172.27.25.35:7000@17000 myself,master - 0 1526287368000 1 connected 0-5460

您好，报错了，好像是解析主从节点信息的时候出错了。

**Comment by GoDannyLai** [comment]
已经修复

**Comment by marscqy** [comment]
thanks..^_^
